---
apiVersion: v1
kind: Service
metadata:
  name: sillyswapi-db
spec:
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: {{ .Values.appName }}
    name: "{{ .Values.appName }}-db"
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: sillyswapi-api
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: {{ .Values.appName }}
    name: "{{ .Values.appName }}-api"
  type: ClusterIP
